//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        public string CompanyName { get; set; }
        public int CountryId { get; set; }
        public int CityId { get; set; }
        public int CompanyId { get; set; }
    }
}
